# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
CONFIG += designer plugin release
HEADERS  = ../IconEditor/IconEditor.h \ 
		   IconEditorPlugin.h
SOURCES  = ../IconEditor/IconEditor.cpp \ 
		   IconEditorPlugin.cpp
RESOURCES = IconEditorPlugin.qrc
DESTDIR = $$[QT_INSTALL_PLUGINS]/designer